### ISSUE TITLE
Add flag or ENV to track keys of a single operator

### ISSUE THREAD

**Issue by dapplion** [lidofinance/ethereum-validators-monitoring#70]
First, thank you so much for open sourcing this useful tool.

Would be useful to expose a configuration param to track only the keys run by a specific node operator. While `VALIDATOR_REGISTRY_SOURCE` can fulfill this request, the proposed approach would require updating the list of keys on new submissions.

**Comment by vgorkavenko** [comment]
Hi, @dapplion! 

You can use **NodeOperators** dashboard for monitoring specific node operator.

Also, you can restrict alerting. Just add `matchers` key to your [alertmanager config](https://github.com/lidofinance/ethereum-validators-monitoring/blob/main/docker/alertmanager/alertmanager.yml)
For example:
```yaml
global:
  resolve_timeout: 15m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 15s
  repeat_interval: 1h
  matchers:
    - nos_name = "MY_SPECIFIC_NODE_OPERATOR"
  receiver: discord_webhook_default
```
